# Generated by Django 5.2.8 on 2026-02-09 07:44

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(verbose_name='Content', help_text="Content of the note"),
        ),
    ]
