# Generated by Django 5.2.8 on 2026-02-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(help_text='Content of the note'),
        ),
    ]
